metadata:
  name: "Zed OpenGOAL Challenge"
mods:
  zed-chall-1-test:
    repo_owner: "my-opengoal-mods"
    repo_name: "OG-Zed-Challenge-1"
    url: "https://github.com/my-opengoal-mods/OG-Zed-Challenge-1"
    release_date_override: "2023-09-16"
    ignore_versions:
      - "<1.13.1"
    display_name: "Zed OpenGOAL Challenge 1"
    description: "The unseen blade is the deadliest.."
    authors: ["zed"]
    tags: ["challenge", "gameplay-mod"]
    website_url: "https://github.com/my-opengoal-mods/OG-Jak-The-Chicken-Reborn/blob/main/README.md"
    cover_art_url: "https://wallpaperset.com/w/full/7/0/0/52090.jpg"
    thumbnail_art_url: "https://github.com/my-opengoal-mods/OG-Zed-Challenge-1/blob/main/zedOGchall.png?raw=true"


# texture_packs:
#   # TODO - this one actually isn't supported end-to-end yet (no releases)
#   # snowy-legacy:
#   #   repo_owner: "kekdeveloper"
#   #   repo_name: "opengoal-mod-snowy-legacy"
#   #   display_name: "Snowy Legacy"
#   #   description: "Snowy texture pack and snowy weather everywhere."
#   #   authors: ["InnocentMiau"]
#   #   supported_games: ["jak1"]
#   #   tags: []
#   #   thumbnail_art_url: "https://github.com/kekdeveloper/opengoal-mod-snowy-legacy/blob/main/ModImage.png?raw=true"
